# -*- coding: utf-8 -*-
"""Ireland Religious Idendity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkJDMajUMqa3k2-AkEdKxnnikn2YIrrQ
"""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Data Cleaning and Processing
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# ==========================================
# 0. SETUP
# ==========================================

# dup_check = df.groupby(["ed", "year", "religion"]).size()
# print(dup_check[dup_check > 1].head(20))


import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import re
import time
from mpl_toolkits.axes_grid1 import make_axes_locatable
from IPython.display import display, clear_output
import pickle
from PIL import Image
from matplotlib.colors import TwoSlopeNorm
import ipywidgets as widgets
import os
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.cm as cm


debugMap = False
debugDeep = False
debugLight = False
debugLong = False
debugFinal = True
# from google.colab import drive # Drive was used in project construction, removed for github compabatility
# drive.mount("/content/drive", force_remount=True)
if debugDeep:
  	print("\n[INFO] Environment ready\n")


# ==========================================
# 1. FILE PATHS
# ==========================================
file_path = "Ireland_Religion_ESC.xlsx"
geo_path = "CSO_ELECTORAL_DIVISIONS_2022.gpkg"
savePath = "/content/drive/MyDrive/ESC/FinalGraphs"
if debugDeep:
  print("[INFO] File paths set")



# ==========================================
# 2. LOAD DATA
# ==========================================
print("\n[STEP 2] Loading data...")

df2011 = pd.read_excel(file_path, sheet_name="Religion2011")
df2016 = pd.read_excel(file_path, sheet_name="Religion2016")
df2022 = pd.read_excel(file_path, sheet_name="Religion2022")
dfAge = pd.read_excel(file_path, sheet_name="ReligionAge")

gdf = gpd.read_file(geo_path)
if debugDeep:
  print("[DEBUG] Shapes:")
  print("2011:", df2011.shape)
  print("2016:", df2016.shape)
  print("2022:", df2022.shape)
  print("dfAge:", dfAge.shape)
  print("GIS:", gdf.shape)

  print("\n[DEBUG] GIS Columns:", gdf.columns.tolist())


# ==========================================
# 3. CLEAN CSO DATA
# ==========================================
print("\n[STEP 3] Cleaning CSO data...")

def clean(df, year):
    df = df.copy()
    if debugDeep:
      print(f"\n[DEBUG] Cleaning year {year}")
      print("Columns BEFORE:", df.columns.tolist())

    if "Electoral Division" in df.columns:
        df = df.rename(columns={"Electoral Division": "ed"})
    elif "CSO Electoral Divisions 2022" in df.columns:
        df = df.rename(columns={"CSO Electoral Divisions 2022": "ed"})

    df.columns = df.columns.str.lower()
    df["year"] = year

    # Filter for 'both sexes' if 'sex' column exists and contains 'both sexes'
    if 'sex' in df.columns and 'both sexes' in df['sex'].unique():
        df = df[df['sex'] == 'both sexes']
    elif 'sex' in df.columns and debugDeep:
        print(f"[DEBUG] 'both sexes' not found in 'sex' column for year {year}. Keeping all sexes.")

    # Filter for 'all ages' if 'age group' column exists and contains 'all ages'
    if 'age group' in df.columns and 'all ages' in df['age group'].unique():
        df = df[df['age group'] == 'all ages']
    elif 'age group' in df.columns and debugDeep:
        print(f"[DEBUG] 'all ages' not found in 'age group' column for year {year}. Keeping all age groups.")

    if debugDeep:
      print("Columns AFTER:", df.columns.tolist())
      print("Sample ED values:", df["ed"].head(3).tolist())

    return df


df = pd.concat([
    clean(df2011, 2011),
    clean(df2016, 2016),
    clean(df2022, 2022)
], ignore_index=True)
if debugDeep:
  print("\n[DEBUG] Combined DF shape:", df.shape)


# ==========================================
# 4. REMOVE TOTAL ROWS
# ==========================================
if debugLight:
  print("\n[STEP 4] Removing total rows...")

before = len(df)
df = df[~df["ed"].str.contains("total", case=False, na=False)]
after = len(df)
if debugDeep:
  print(f"[DEBUG] Rows before: {before}, after: {after}, removed: {before - after}")

# Debug
dup_check = df.groupby(["ed", "year", "religion"]).size()
print("Duplication check: ", dup_check[dup_check > 1].head(20))



# ==========================================
# 5. PIVOT
# ==========================================
if debugLight:
  print("\n[STEP 5] Pivoting data...")

wideDF = df.pivot_table(
    index=["ed", "year"],
    columns="religion",
    values="value",
    aggfunc="sum"
).reset_index()

def split_ed(x):
    # This regex removes the 5-digit code like ", 08028"
    x_clean = re.sub(r',\s*\d{5}$', '', str(x))
    parts = x_clean.split(",")
    name = parts[0].strip().upper()
    # Normalize County: "Co. Laois" -> "LAOIS"
    county = parts[1].replace("Co.", "").replace("County", "").strip().upper() if len(parts) > 1 else None
    return pd.Series([name, county])


if debugDeep:
  print("[DEBUG] Wide DF shape:", wideDF.shape)
  print("[DEBUG] Columns:", wideDF.columns.tolist())
  print("[DEBUG] Sample:\n", wideDF.head())


# ==========================================
# 6. NORMALISATION, DISSOLVE & GAEILGE FIX
# ==========================================
import unicodedata

def strip_accents(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', str(s))
        if unicodedata.category(c) != 'Mn'
    )

def pro_clean(x):
    if pd.isna(x): return ""
    x = str(x).upper()
    x = re.sub(r'\(.*\)', '', x)
    for word in ["COUNTY", "CITY", "CO.", "CO ", "URB", "RUR"]:
        x = x.replace(word, "")
    x = x.replace("'", "").replace(".", "").replace("-", " ")
    x = x.replace("Θ", "É").replace("┴", "Á")
    x = x.strip()

    encoding_fixes = {
    "Θ": "É", "┴": "Á", "≤": "Ó", "·": "Ú", "Φ": "Í",
    "SSN": "ÁN",  # e.g. CLOCHSSN -> CLOCHÁN
    "BHSSN": "BHÁN", "CORRSSN": "CORRÁN", "CNOCSSN": "CNOCÁN",
    "CROMPSSN": "CROMPÁN",
}
    for bad, good in encoding_fixes.items():
        x = x.replace(bad, good)

    county_map = {
        # English variants
        "NORTH TIPPERARY":        "TIPPERARY",
        "SOUTH TIPPERARY":        "TIPPERARY",
        "DUN LAOGHAIRE/RATHDOWN": "DÚN LAOGHAIRE RATHDOWN",
        # Irish county names → English (to match GIS file)
        "AN MHÍ":                 "MEATH",
        "CATHAIR NA GAILLIMHE":   "GALWAY",
        "CIARRAÍ":                "KERRY",
        "CORCAIGH":               "CORK",
        "DÚN LAOGHAIRE RATHDOWN": "DÚN LAOGHAIRE RATHDOWN",
        "DUN LAOGHAIRE RATHDOWN": "DÚN LAOGHAIRE RATHDOWN",
        "DUN LAOGHAIRE/RATHDOWN": "DÚN LAOGHAIRE RATHDOWN",
        "DUN LAOGHAIRE": "DÚN LAOGHAIRE RATHDOWN",
        "DÚN NA NGALL":           "DONEGAL",
        "GAILLIMH":               "GALWAY",
        "MAIGH EO":               "MAYO",
        "PORT LÁIRGE":            "WATERFORD",
        "TIPPERARY":              "TIPPERARY",
    }
    # x = strip_accents(x)
    return county_map.get(x, x)



wideDF[["ed_name", "county"]] = wideDF["ed"].apply(split_ed)
wideDF["ed_name"] = wideDF["ed_name"].apply(pro_clean)
wideDF["county"]  = wideDF["county"].apply(pro_clean)

# Collapse split EDs
numeric_cols = ["Catholic", "No religion", "Not stated", "Other religion", "Total"]
wideDF = wideDF.groupby(["ed_name", "county", "year"], as_index=False)[numeric_cols].sum()

#  lookup tables from GIS: English, Irish
gdf["ed_eng"]  = gdf["ED_ENGLISH"].apply(pro_clean)
gdf["ed_irl"]  = gdf["ED_GAEILGE"].apply(pro_clean)
gdf["co_eng"]  = gdf["COUNTY_ENGLISH"].apply(pro_clean)
gdf["co_irl"]  = gdf["COUNTY_GAEILGE"].apply(pro_clean)

print("[INFO] Dissolving GIS geometries...")
gdf_eng = gdf.dissolve(by=["ed_eng", "co_eng"]).reset_index()[["ed_eng", "co_eng", "geometry"]]
gdf_irl = gdf.dissolve(by=["ed_irl", "co_irl"]).reset_index()[["ed_irl", "co_irl", "geometry"]]

gis_counties = set(gdf["co_eng"].unique())
cso_counties = set(wideDF["county"].unique())

print("In GIS but not CSO:", sorted(gis_counties - cso_counties))
print("In CSO but not GIS:", sorted(cso_counties - gis_counties))

dlr_ed_prefixes = [
    "DUN LAOGHAIRE", "DÚN LAOGHAIRE",
    "DALKEY", "DUNDRUM", "STILLORGAN",
    "KILLINEY", "SHANKILL", "DEANSGRANGE",
    "BALLYBRACK", "CABINTEELY", "CHERRYWOOD",
    "FOXROCK", "GLENCULLEN", "LOUGHLINSTOWN",
]

def fix_county_from_ed_name(row):
    if row["county"] == "DUBLIN":
        for prefix in dlr_ed_prefixes:
            if row["ed_name"].startswith(prefix):
                return "DÚN LAOGHAIRE RATHDOWN"
    return row["county"]

wideDF["county"] = wideDF.apply(fix_county_from_ed_name, axis=1)


# ==========================================
# 8. THREE-PASS MERGE
# ==========================================

# Pass 1: match on English names
geoDF = wideDF.merge(
    gdf_eng.rename(columns={"ed_eng": "ed_name", "co_eng": "county"}),
    on=["ed_name", "county"],
    how="left"
)

# Pass 2: for still-unmatched rows,  Irish names
unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():

    unmatched_rows = geoDF.loc[unmatched_mask, ["ed_name", "county", "year"] + numeric_cols]

    irish_fill = unmatched_rows.merge(
        gdf_irl.rename(columns={"ed_irl": "ed_name", "co_irl": "county"}),
        on=["ed_name", "county"],
        how="left"
    )


    geoDF.loc[unmatched_mask, "geometry"] = irish_fill["geometry"].values

print(f"Match rate after two-pass: {geoDF['geometry'].notna().mean():.2%}")
print(f"Null geometries remaining: {geoDF['geometry'].isna().sum()}")

# Pass 3: prefix match for new 2022 sub-EDs
unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():

    gdf_name_only = gdf_eng.groupby("ed_eng").first().reset_index()[["ed_eng", "co_eng", "geometry"]]

    unmatched_rows = geoDF.loc[unmatched_mask, ["ed_name", "county", "year"]].copy()

    def find_prefix_match(row, lookup):
        """Try progressively shorter prefixes until a match is found"""
        name = row["ed_name"]
        county = row["county"]
        words = name.split()
        for i in range(len(words) - 1, 0, -1):
            prefix = " ".join(words[:i])
            match = lookup[
                (lookup["ed_eng"] == prefix) &
                (lookup["co_eng"] == county)
            ]
            if len(match) == 1:
                return match["geometry"].iloc[0]
        return None

    prefix_geoms = unmatched_rows.apply(
        lambda row: find_prefix_match(row, gdf_name_only), axis=1
    )
    geoDF.loc[unmatched_mask, "geometry"] = prefix_geoms.values
geoDF = geoDF[geoDF["ed_name"] != "IRELAND"]

print(f"Match rate after pass 3: {geoDF['geometry'].notna().mean():.2%}")
print(f"Still unmatched: {geoDF['geometry'].isna().sum()}")
still_null = geoDF[geoDF["geometry"].isna()][["ed_name","county","year"]].drop_duplicates()
print(still_null.head(20))

# Pass 4: slash-name
unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    unmatched_rows = geoDF.loc[unmatched_mask, ["ed_name", "county", "year"]].copy()

    def find_slash_match(row, lookup):
        name = row["ed_name"]
        county = row["county"]
        if "/" not in name:
            if debugFinal:
              print(f"No / found in row={row}, lookup={lookup}")
            return None
        first_part = name.split("/")[0].strip()
        match = lookup[
            (lookup["ed_eng"] == first_part) &
            (lookup["co_eng"] == county)
        ]
        if len(match) >= 1:
            return match["geometry"].iloc[0]
        return None

    slash_geoms = unmatched_rows.apply(
        lambda row: find_slash_match(row, gdf_name_only), axis=1
    )
    geoDF.loc[unmatched_mask, "geometry"] = slash_geoms.values

print(f"Match rate after pass 4: {geoDF['geometry'].notna().mean():.2%}")
print(f"Still unmatched: {geoDF['geometry'].isna().sum()}")

# Pass 5: match on parent ED name (DALKEY <= DALKEY AVONDALE)
unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    # Dissolve GIS polygons, grouping sub-EDs under parent name
    gdf_parent = gdf_eng.copy()
    gdf_parent["parent"] = gdf_parent["ed_eng"].str.split().str[0]
    gdf_parent = gdf_parent.dissolve(by=["parent", "co_eng"]).reset_index()

    unmatched_rows = geoDF.loc[unmatched_mask, ["ed_name", "county", "year"]].copy()
    unmatched_rows["parent"] = unmatched_rows["ed_name"].str.split().str[0]

    parent_fill = unmatched_rows.merge(
        gdf_parent.rename(columns={"parent": "parent", "co_eng": "county"}),
        on=["parent", "county"],
        how="left"
    )
    geoDF.loc[unmatched_mask, "geometry"] = parent_fill["geometry"].values


print(f"Match rate after pass 5: {geoDF['geometry'].notna().mean():.2%}")

# Pass 6: DLR 2022 new sub-EDs, match by ED name prefix
unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    dlr_mask = unmatched_mask & geoDF["county"].str.contains("LAOGHAIRE", na=False)
    if dlr_mask.any():
        unmatched_dlr = geoDF.loc[dlr_mask, ["ed_name", "county", "year"]].copy()
        unmatched_dlr["parent"] = unmatched_dlr["ed_name"].str.split().str[:2].str.join(" ")

        gdf_dlr = gdf_eng[gdf_eng["co_eng"].str.contains("LAOGHAIRE", na=False)].copy()
        gdf_dlr["parent"] = gdf_dlr["ed_eng"].str.split().str[:2].str.join(" ")
        gdf_dlr_dissolved = gdf_dlr.dissolve(by="parent").reset_index()[["parent", "geometry"]]

        dlr_fill = unmatched_dlr.merge(gdf_dlr_dissolved, on="parent", how="left")
        geoDF.loc[dlr_mask, "geometry"] = dlr_fill["geometry"].values

print(f"Match rate after pass 6: {geoDF['geometry'].notna().mean():.2%}")
print(gdf_eng[gdf_eng["ed_eng"].str.startswith("D", na=False) &
              gdf_eng["co_eng"].str.contains("LAOGHAIRE", na=False)]["ed_eng"].unique())

dup_final = geoDF.groupby(["ed_name", "county", "year"]).size()
print("Remaining duplicates:", dup_final[dup_final > 1])


DUBLIN_COUNTIES = ["DUBLIN", "FINGAL", "SOUTH DUBLIN", "DUN LAOGHAIRE RATHDOWN"]

unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    gdf_dublin_all = gdf_eng[gdf_eng["co_eng"].isin(DUBLIN_COUNTIES)][["ed_eng","geometry"]].drop_duplicates("ed_eng")

    dublin_idx = geoDF.index[unmatched_mask & (geoDF["county"] == "DUBLIN")]
    for idx in dublin_idx:
        name = geoDF.at[idx, "ed_name"]
        match = gdf_dublin_all[gdf_dublin_all["ed_eng"] == name]
        if len(match) == 1:
            geoDF.at[idx, "geometry"] = match["geometry"].iloc[0]

print(f"Match rate after Dublin loop pass: {geoDF['geometry'].notna().mean():.2%}")

unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    import unicodedata
    def strip_accents(s):
        return ''.join(
            c for c in unicodedata.normalize('NFD', str(s))
            if unicodedata.category(c) != 'Mn'
        )

    # Build accent-stripped Irish GIS lookup
    gdf_irl_stripped = gdf_irl.copy()
    gdf_irl_stripped["ed_irl"] = gdf_irl_stripped["ed_irl"].apply(strip_accents).str.upper()
    gdf_irl_stripped["co_irl"] = gdf_irl_stripped["co_irl"].apply(strip_accents).str.upper()

    unmatched_rows = geoDF.loc[unmatched_mask, ["ed_name", "county", "year"]].copy()
    unmatched_rows["ed_stripped"] = unmatched_rows["ed_name"].apply(strip_accents)
    unmatched_rows["co_stripped"] = unmatched_rows["county"].apply(strip_accents)

    irish_stripped_fill = unmatched_rows.merge(
        gdf_irl_stripped.rename(columns={"ed_irl": "ed_stripped", "co_irl": "co_stripped"}),
        on=["ed_stripped", "co_stripped"],
        how="left"
    )
    geoDF.loc[unmatched_mask, "geometry"] = irish_stripped_fill["geometry"].values

print(f"Match rate after stripped Irish pass: {geoDF['geometry'].notna().mean():.2%}")

unmatched_mask = geoDF["geometry"].isna()
dlr_2022 = geoDF.index[unmatched_mask & (geoDF["year"] == 2022) & geoDF["county"].str.contains("LAOGHAIRE", na=False)]
for idx in dlr_2022:
    name_stripped = strip_accents(geoDF.at[idx, "ed_name"])
    match = gdf_eng[gdf_eng["ed_eng"] == name_stripped]
    if len(match) >= 1:
        geoDF.at[idx, "geometry"] = match["geometry"].iloc[0]

print(f"After DLR 2022 targeted pass: {geoDF['geometry'].notna().mean():.2%}")


unmatched_mask = geoDF["geometry"].isna()
if unmatched_mask.any():
    from difflib import get_close_matches
    gdf_irl_names = gdf_irl["ed_irl"].apply(strip_accents).str.upper().tolist()

    for idx in geoDF.index[unmatched_mask]:
        name = strip_accents(geoDF.at[idx, "ed_name"])
        county = strip_accents(geoDF.at[idx, "county"])

        county_gis = gdf_irl[gdf_irl["co_irl"].apply(strip_accents).str.upper() == county]
        if len(county_gis) == 0:
            continue
        candidates = county_gis["ed_irl"].apply(strip_accents).str.upper().tolist()
        matches = get_close_matches(name, candidates, n=1, cutoff=0.8)
        if matches:
            geom = county_gis[county_gis["ed_irl"].apply(strip_accents).str.upper() == matches[0]]["geometry"]
            if len(geom) == 1:
                geoDF.at[idx, "geometry"] = geom.iloc[0]

print(f"After fuzzy Irish pass: {geoDF['geometry'].notna().mean():.2%}")
print(f"Still unmatched: {geoDF['geometry'].isna().sum()}")

# DLR, not Dublin city
DLR_PREFIXES = [
    "BALLINTEER", "BLACKROCK", "BALLYBRACK", "CABINTEELY",
    "DALKEY", "DUNDRUM", "DEANSGRANGE", "FOXROCK", "GLENCULLEN",
    "KILLINEY", "LOUGHLINSTOWN", "SANDYFORD", "SHANKILL",
    "STILLORGAN", "CHERRYWOOD"
]

unmatched_mask = geoDF["geometry"].isna()
gdf_dlr = gdf_eng[gdf_eng["co_eng"] == "DUN LAOGHAIRE RATHDOWN"]

for idx in geoDF.index[unmatched_mask & (geoDF["county"] == "DUBLIN")]:
    name = geoDF.at[idx, "ed_name"]

    prefix = name.split()[0]
    if prefix in DLR_PREFIXES:
        match = gdf_dlr[gdf_dlr["ed_eng"] == name]
    else:

        match = gdf_eng[gdf_eng["co_eng"].isin(DUBLIN_COUNTIES) & (gdf_eng["ed_eng"] == name)]
    if len(match) >= 1:
        geoDF.at[idx, "geometry"] = match["geometry"].iloc[0]

print(f"Match rate after DLR prefix pass: {geoDF['geometry'].notna().mean():.2%}")

# VALIDATION: 0 if the dissolve worked
dup_final = geoDF.groupby(["ed_name", "county", "year"]).size()
print("Final Duplication Check (Should be empty):", dup_final[dup_final > 1])

if debugDeep:
  print("[DEBUG] Merged shape:", geoDF.shape)
  print("Len geoDF, wideDF", len(geoDF), len(wideDF))

null_geom = geoDF["geometry"].isna().sum()
if debugDeep:
  print(f"[DEBUG] Null geometries: {null_geom}")

match_rate = geoDF["geometry"].notna().mean()
if debugDeep:
  print(f"[DEBUG] Match rate: {match_rate:.2%}")

dup_clean = wideDF.groupby(["ed_name", "county", "year"]).size()
print("Duplication check clean: ", dup_clean[dup_clean > 1].head(20))

# dup_geo = gdf_clean.groupby(["ed_name", "county"]).size()
# print("Duplicates in gdf_clean (post-dissolve):", dup_geo[dup_geo > 1].head(20))

unmatched = geoDF[geoDF["geometry"].isna()][["ed_name", "county", "year"]].drop_duplicates()
print(f"Unmatched:\n", unmatched[unmatched["year"] == 2022].head(20))

print(f"=====================================================================================")
sample_miss = "ABINGTON"
print("In wideDF:", wideDF[wideDF["ed_name"] == sample_miss][["ed_name","county"]].drop_duplicates())
print("In gdf_eng:", gdf_eng[gdf_eng["ed_eng"].str.contains(sample_miss, na=False)][["ed_eng","co_eng"]])

print("Check what's actually in gdf_eng for DLR")

print(gdf_eng[gdf_eng["co_eng"].str.contains("LAOGHAIRE", na=False)]["ed_eng"].head(20))

# Check what parents are being generated for the unmatched rows
unmatched_dlr_check = geoDF[geoDF["geometry"].isna() & geoDF["county"].str.contains("LAOGHAIRE", na=False)]
print("CSO parents:", unmatched_dlr_check["ed_name"].str.split().str[:2].str.join(" ").unique())

# sub-ED names without the DLR prefix
print("specific sub-ED names without the DLR prefix:")
for name in ["GLASTHULE", "SANDYCOVE", "SALLYNOGGIN", "GLENAGEARY",
             "MONKSTOWN", "SALTHILL", "MOUNT TOWN"]:
    result = gdf_eng[gdf_eng["ed_eng"].str.contains(name, na=False)][["ed_eng","co_eng"]]
    if len(result):
        print(result)
    else:
        print(f"NOT FOUND: {name}")


print("Sample co_eng values:", gdf["co_eng"].unique()[:5])
print("Sample county values:", wideDF["county"].unique()[:5])


dublin_unmatched = geoDF[geoDF['geometry'].isna() & (geoDF['county'] == 'DUBLIN')]
print(dublin_unmatched[['ed_name','county','year']].drop_duplicates().head(30))

donegal_unmatched = geoDF[geoDF['geometry'].isna() & (geoDF['county'] == 'DONEGAL')]
print(donegal_unmatched['ed_name'].drop_duplicates().head(20))

dublin_2022 = geoDF[(geoDF["year"] == 2022) & geoDF["county"].str.contains("DUBLIN|FINGAL|SOUTH", na=False, case=False)]
print(dublin_2022[["ed_name","county","year"]].head(20))
print("\nCounty value counts for Dublin area 2022:")
print(dublin_2022["county"].value_counts())

# Compare 2011 vs 2022 Dublin row counts
print("\nDublin rows by year:")
print(geoDF[geoDF["county"].str.contains("DUBLIN|FINGAL|SOUTH|LAOGHAIRE", na=False, case=False)].groupby("year").size())

DUBLIN_FAMILY = {"FINGAL", "SOUTH DUBLIN", "DUBLIN CITY",
                 "DUN LAOGHAIRE RATHDOWN", "DÚN LAOGHAIRE RATHDOWN"}
geoDF["county_key"] = geoDF["county"].apply(
    lambda x: "DUBLIN" if x in DUBLIN_FAMILY else x
)
print("=" * 60)
dublin_2022 = geoDF[(geoDF["year"] == 2022) & geoDF["county"].str.contains("DUBLIN|FINGAL|SOUTH", na=False, case=False)]
print(dublin_2022[["ed_name","county","year"]].head(20))
print("\nCounty value counts for Dublin area 2022:")
print(dublin_2022["county"].value_counts())

# Compare 2011 vs 2022 Dublin row counts
print("\nDublin rows by year:")
print(geoDF[geoDF["county"].str.contains("DUBLIN|FINGAL|SOUTH|LAOGHAIRE", na=False, case=False)].groupby("year").size())
dup_final = geoDF.groupby(["ed_name", "county", "year"]).size()
print("Final Duplication Check (Should be empty):", dup_final[dup_final > 1])

print("=" * 60)
print("TEST 1: GEOMETRY VALIDITY")
print("=" * 60)

total_rows = len(geoDF)
null_geom = geoDF["geometry"].isna().sum()
valid_geom = geoDF["geometry"].notna().sum()

print(f"Total rows: {total_rows}")
print(f"Valid geometries: {valid_geom} ({valid_geom/total_rows:.1%})")
print(f"Null geometries: {null_geom} ({null_geom/total_rows:.1%})")

# Check for invalid (malformed) geometries separately
geoDF_valid = geoDF[geoDF["geometry"].notna()].copy()
geoDF_valid = gpd.GeoDataFrame(geoDF_valid, geometry="geometry")
invalid_geom = (~geoDF_valid.geometry.is_valid).sum()
print(f"Malformed geometries (not null but invalid): {invalid_geom}")

# By year
print("\nBy year:")
print(geoDF.groupby("year")["geometry"].apply(lambda x: x.notna().sum()).rename("valid"))
print(geoDF.groupby("year")["geometry"].apply(lambda x: x.isna().sum()).rename("null"))

print("=" * 60)
print("TEST 2: NaN IN RELIGION COLUMNS")
print("=" * 60)

religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]
for col in religion_cols:
    null_count = geoDF[col].isna().sum()
    zero_count = (geoDF[col] == 0).sum()
    print(f"{col}: {null_count} NaN, {zero_count} zeros")

# Rows where total is zero
total = geoDF[religion_cols].sum(axis=1)
zero_total = (total == 0).sum()
print(f"\nRows where all religion cols sum to 0: {zero_total}")
print(geoDF[total == 0][["ed_name", "county", "year"]].head(10))

print("=" * 60)
print("TEST 3: SIMULATE PLOT RENDERING")
print("=" * 60)

religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]

for year in [2011, 2016, 2022]:
    print(f"\n === Year {year} === ")
    mapDF = geoDF[geoDF["year"] == year].copy()

    total_eds = len(mapDF)
    has_geom = mapDF["geometry"].notna().sum()

    total = mapDF[religion_cols].sum(axis=1)
    mapDF["Catholic_pct"] = mapDF["Catholic"] / total.replace(0, float("nan"))

    has_pct = mapDF["Catholic_pct"].notna().sum()
    has_both = (mapDF["geometry"].notna() & mapDF["Catholic_pct"].notna()).sum()

    print(f"  Total EDs: {total_eds}")
    print(f"  Has geometry: {has_geom} ({has_geom/total_eds:.1%})")
    print(f"  Has valid pct: {has_pct} ({has_pct/total_eds:.1%})")
    print(f"  Has both (will render): {has_both} ({has_both/total_eds:.1%})")
    print(f"  Probably blank on map: {total_eds - has_both} ({(total_eds-has_both)/total_eds:.1%})")


print("=" * 60)
print("TEST 4: SIMULATE DIVERGE RENDERING")
print("=" * 60)

religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]
DUBLIN_FAMILY = {"FINGAL", "SOUTH DUBLIN", "DUBLIN CITY",
                 "DUN LAOGHAIRE RATHDOWN", "DÚN LAOGHAIRE RATHDOWN"}
geoDF["county_key"] = geoDF["county"].apply(
    lambda x: "DUBLIN" if x in DUBLIN_FAMILY else x
)

def get_pct(df, religion):
    df = df.copy()
    total = df[religion_cols].sum(axis=1)
    df[f"{religion}_pct"] = df[religion] / total.replace(0, float("nan"))
    return df

base = geoDF[geoDF["year"] == 2011].copy().set_index(["ed_name", "county_key"])
base = get_pct(base, "Catholic")

for year in [2016, 2022]:
    curr = geoDF[geoDF["year"] == year].copy()
    curr = curr.set_index(["ed_name", "county_key"])

    currentMap = get_pct(curr, "Catholic")
    base["Catholic_pct"].reindex(currentMap.index)
    plotMap = currentMap.copy()
    # print(currentMap.head(20))
    dup_final = currentMap.groupby(["ed_name", "county", "year"]).size()
    print(" Duplication Check (would be class if empty):", dup_final[dup_final > 1])
    plotMap[f"Catholic_pct"] = currentMap[f"Catholic_pct"] - base[f"Catholic_pct"]


    plotMap["diff"] = plotMap[f"Catholic_pct"]

    total = len(plotMap)
    renderable = (plotMap["diff"].notna() & plotMap["geometry"].notna()).sum()
    nan_diff = plotMap["diff"].isna().sum()
    null_geom = plotMap["geometry"].isna().sum()


    missing_from_curr = base.index.difference(curr.index)
    missing_from_base = curr.index.difference(base.index)

    print(f"\n === Diverge: 2011 {year} ===")
    print(f"  Renderable rows: {renderable}/{total} ({renderable/total:.1%})")
    print(f"  NaN diff (index mismatch): {nan_diff}")
    print(f"  Null geometry: {null_geom}")
    print(f"  EDs in 2011 not in {year}: {len(missing_from_curr)}")
    print(f"  EDs in {year} not in 2011: {len(missing_from_base)}")
    if len(missing_from_base) > 0:
        print(f"  New EDs sample: {list(missing_from_base[:5])}")
    if len(missing_from_curr) > 0:
        print(f"  Dropped EDs sample: {list(missing_from_curr[:5])}")

print("=" * 60)
print("TEST 5: VISUAL COVERAGE MAP")
print("=" * 60)

import matplotlib.patches as mpatches

religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]
fig_test, axes = plt.subplots(1, 3, figsize=(18, 8))

for i, year in enumerate([2011, 2016, 2022]):
    ax_t = axes[i]
    mapDF = geoDF[geoDF["year"] == year].copy()
    total = mapDF[religion_cols].sum(axis=1)
    mapDF["Catholic_pct"] = mapDF["Catholic"] / total.replace(0, float("nan"))
    mapDF["renderable"] = (mapDF["geometry"].notna() & mapDF["Catholic_pct"].notna()).astype(int)

    mapDF = gpd.GeoDataFrame(mapDF, geometry="geometry")


    mapDF[mapDF["renderable"] == 1].plot(ax=ax_t, color="green", alpha=0.5)
    mapDF[mapDF["renderable"] == 0].plot(ax=ax_t, color="red", alpha=0.8)

    n_render = mapDF["renderable"].sum()
    n_total = len(mapDF)
    ax_t.set_title(f"{year}: {n_render}/{n_total} ({n_render/n_total:.1%}) renderable")
    ax_t.set_axis_off()

    green_patch = mpatches.Patch(color='green', alpha=0.5, label='Renders')
    red_patch = mpatches.Patch(color='red', alpha=0.8, label='Missing')
    ax_t.legend(handles=[green_patch, red_patch], loc='lower left')

plt.tight_layout()
plt.savefig(f"{savePath}/coverage_diagnostic.png", dpi=200, bbox_inches='tight')
plt.show()
print("Saved coverage map")

print("=" * 60)
print("TEST 6: COVERAGE BY COUNTY AND YEAR")
print("=" * 60)

religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]

results = []
for year in [2011, 2016, 2022]:
    mapDF = geoDF[geoDF["year"] == year].copy()
    total = mapDF[religion_cols].sum(axis=1)
    mapDF["pct"] = mapDF["Catholic"] / total.replace(0, float("nan"))
    mapDF["renderable"] = mapDF["geometry"].notna() & mapDF["pct"].notna()

    by_county = mapDF.groupby("county")["renderable"].agg(["sum", "count"])
    by_county["year"] = year
    by_county["pct_renderable"] = by_county["sum"] / by_county["count"]
    results.append(by_county)

result_df = pd.concat(results).reset_index()

# counties with poor coverage
poor = result_df[result_df["pct_renderable"] < 0.90].sort_values("pct_renderable")
print("Counties with <90% coverage:")
print(poor[["county", "year", "sum", "count", "pct_renderable"]].to_string())

def save(savedItem, name):
  fileName = f"{name}.pkl"
  fullPath = os.path.join("/content/drive/MyDrive/ESC", fileName)
  if not os.path.exists("/content/drive/MyDrive/ESC"):
    print(f"Oh.")
  with open(fullPath, 'wb') as f:
    pickle.dump(savedItem, f)
  print(f"Done.")

def load(savedItem, name):
  fileName = f"{name}.pkl"
  fullPath = os.path.join("/content/drive/MyDrive/ESC", fileName)
  if not os.path.exists("/content/drive/MyDrive/ESC"):
    print(f"Oh.")
  with open(fullPath, 'rb') as f:
    pickle.load(savedItem, f)
  print(f"Done.")

titleSize = 12
titleWeight = 'bold'

# =====================================================
# configuration for scales and colors
# =====================================================



brbg = cm.get_cmap('BrBG')
green_mid = brbg(0.65)   # light green
green_dark = brbg(0.85)  # dark green
green_max = brbg(1.0)    # darkest green

copper_white_green = LinearSegmentedColormap.from_list(
    'copper_white_green',
    [
        '#8B4513',  # dark copper (max neg)
        '#C47722',  # mid copper
        '#E8A857',  # light copper
        'snow',  # white (zero)
        green_mid,  #from BrBG
        green_dark,
        green_max,
    ]
)

limit = 0.15
mapConfig = {
    'Catholic':       {'cmap': copper_white_green,    'std_cmap': 'Blues',   'limit': limit, 'std_max': 0.90},
    'No religion':    {'cmap': 'RdBu',    'std_cmap': 'Purples', 'limit': limit, 'std_max': 0.40},
    'Other religion': {'cmap': 'PuOr',    'std_cmap': 'Oranges', 'limit': 0.05, 'std_max': 0.40},
    'Not stated': {'cmap': 'PiYG',    'std_cmap': 'copper', 'limit': 0.2, 'std_max': 0.40},
    'Grouped':        {'cmap': 'viridis', 'std_max': 1.0}
}

years = [2011, 2016, 2022]
map1 = {}

# =====================================================
# Numbers Woo
# =====================================================

# statsDict = {
#     "No religion": {
#         "Diverged": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         },
#         "Standard": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         }
#       },
#     "Not stated": {
#         "Diverged": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         },
#         "Standard": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         }
#       },
#     "Other religion": {
#         "Diverged": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         },
#         "Standard": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         }
#       },
#     "Catholic": {
#         "Diverged": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         },
#         "Standard": {
#           'avg': {},
#           'min': {},
#           'max': {},
#           'std': {}
#         }
#       },

#     'avg': {},
#     'min': {},
#     'max': {},
#     'std': {}
#     }

# statsDict2 = {
#     'avg': {},
#     'min': {},
#     'max': {},
#     'std': {}
# }

statsList3 = []

# statsDF = pd.DataFrame(statsColumns)

def getNum(df, rawDF, col, title, mode, religion, year):
  global statsList3

  # Average
  avg = df[col].mean()
  # statsDict[religion][mode]["avg"][year] = avg
  # Largest change
  minVal = df[col].min()
  minInd = df.loc[df[col] == minVal, 'ed_name'].iloc[0]
  # statsDict[religion][mode]["min"][year] = min

  maxVal = df[col].max()
  columnList = df.columns.tolist()
  # print(f"columnList {columnList}")
  maxInd = df.loc[df[col] == maxVal, 'ed_name'].iloc[0]
  # print(f"maxInd {maxInd}")
  # statsDict[religion][mode]["max"][year] = max

  # Std
  std = df[col].std()
  # statsDict[religion][mode]["std"][year] = std
  # total = df[col].sum(axis=0)

  if hasattr(rawDF, 'sum'):
        total = rawDF.sum()
  else:
      total = rawDF

  if debugLong:
    print(f"{religion}, {mode}, {rawDF}")
  total = rawDF.sum()

  row = {
      "Religion": religion,
      "Mode": mode,
      "Year": year,
      "Avg": avg,
      "Min": minVal,
      "Min Loc": minInd,
      "Max": maxVal,
      "Max Loc": maxInd,
      "std": std,
      "Total": total
  }
  statsList3.append(row)
  # Coeff of distrubution / clustering

  # printing:
  # print(f"{title} Numbers")
# =====================================================
# graphing shtuff
# =====================================================

fig, ax = plt.subplots(figsize=(10,6))

divider = make_axes_locatable(ax)
fig.set_layout_engine(None)
# cax = divider.append_axes("right", size="5%", pad=0.1)
# [left, bottom, width, height] as a fraction of the figure (0 to 1)
cax = fig.add_axes([0.69, 0.1, 0.015, 0.7])

plt.ion()
displayHandle = display(fig, display_id=True)



# =====================================================
# Map function (grouping religions)
# =====================================================

def mapGrouped(df, year, colour, vMax, **kwargs):
  global displayHandle

  ax.clear()
  cax.clear()

  groupDF = df[df['year'] == year].copy()

  total = groupDF[["Catholic", "No religion", "Not stated", "Other religion"]].sum(axis=1)
  religious = groupDF[["Catholic", "Other religion"]].sum(axis='columns')
  if debugMap:
    print(f"total {total}")

  groupDF["pct"] = (
      religious / total
  )

  groupDF = gpd.GeoDataFrame(groupDF, geometry="geometry")
  groupDF.plot(column="pct", ax=ax, cax=cax, legend=True, cmap=colour, vmin=0, vmax=vMax)
  ax.set_title(f"% Idenditfying as Religious ({year})")
  ax.set_axis_off()
  displayHandle.update(fig)
  fig.savefig(f"{savePath}/grouped_religion_{year}", dpi=400, bbox_inches='tight')

# =====================================================
# Standard Map
# =====================================================

def map(df, year, r1, colour, vMax, **kwargs):
  global displayHandle

  title = f"{r1} Share ({year})";
  if debugMap:
    print(r1)
  ax.clear()
  cax.clear()

  mapDF = df[df['year'] == year].copy()
  rawDF = mapDF[r1].copy()

  total = mapDF[["Catholic", "No religion", "Not stated", "Other religion"]].sum(axis=1)
  if debugMap:
    print(f"total {total}")

  mapDF[f"{r1}_pct"] = (
      mapDF[r1] / total)
  if debugMap:
    print(f"map[{r1}_pct {mapDF[f"{r1}_pct"]}, map[r1] {mapDF[r1]}")
  mapDF = gpd.GeoDataFrame(mapDF, geometry="geometry")
  mapDF.plot(column=f"{r1}_pct", ax=ax, cax=cax, legend=True, cmap=colour, vmin=0, vmax=vMax)
  ax.set_title(title)
  ax.set_axis_off()
  displayHandle.update(fig)
  fig.savefig(f"{savePath}/{r1}_{year}", dpi=400, bbox_inches='tight')
  getNum(mapDF, rawDF, f"{r1}_pct", title, 'Standard', r1, year)

# def mapDiverge(df, year, r1, colour, isFirst, **kwargs):
#   global displayHandle, map1
#   df = df.copy()
#   dfBig = {}
#   if debugMap:
#     print(r1)
#   ax.clear
#   cax.clear


#   def getPct(map, r1):
#     map = map.copy()
#     total = map[["Catholic", "No religion", "Not stated", "Other religion"]].sum(axis=1)
#     if debugMap:
#       print(f"total {total}")

#     map[f"{r1}_pct"] = (
#       map[r1] / total
#     )
#     if debugMap:
#       print(f"map[{r1}_pct {map[f"{r1}_pct"}], map[r1] {map[r1]}")
#     return map

#   # for i in range(len(yearList)+1):
#   if isFirst:
#     map1 = df[df['year'] == year].copy() # first year
#     map1 = getPct(map1, r1)
#     plotMap = map1.copy()
#     plotMap[f"{r1}_pct"] = 0
#     v_min, v_max, v_center = -0.1, 0.1, 0
#   else:
#     currentMap = df[df['year'] == year].copy()
#     currentMap = getPct(currentMap, r1)
#     plotMap = currentMap.copy()
#     plotMap[f"{r1}_pct"] = currentMap[f"{r1}_pct"] - map1[f"{r1}_pct"]

#     actual_min = plotMap[f"{r1}_pct"].min()
#     actual_max = plotMap[f"{r1}_pct"].max()

#     v_limit = max(abs(actual_min), abs(actual_max))
#     if v_limit == 0: v_limit = 0.1 # avoid division by zero
#     v_min, v_max, v_center = -v_limit, v_limit, 0

#   norm = TwoSlopeNorm(vmin=v_min, vcenter=v_center, vmax=v_max)

#   plotMap = gdp.GeoDataFrame(plotMap, geometry="geometry")
#   plotMap.plot(column=f"{r1}_pct", ax=ax, cax=cax, legend=True, cmap=colour, norm=norm)
#   ax.set_title(f"{r1} Share ({year})")
#   ax.set_axis_off()
#   displayHandle.update(fig)
  # fig.savefig(f"{savePath}/{r1}_{year}_diverge", dpi=400, bbox_inches='tight')
  ## with open(f"{savePath}/{r1}_{year}", 'wb') as f:
  ##   pickle.dump()



  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



# def mapDiverge(df, year, r1, colour, isFirst, **kwargs):
#     global displayHandle, map1


#     df_clean = df[df['year'] == year].drop_duplicates(subset=['ed_clean'])
#     df_temp = df_clean.set_index("ed_clean")

#     def getPct(data, religion):
#         data = data.copy()
#         cols = ["Catholic", "No religion", "Not stated", "Other religion"]
#         total = data[cols].sum(axis=1)
#         # Avoid division by zero
#         data[f"{religion}_pct"] = data[religion] / total.replace(0, 1)
#         return data

#     if isFirst:
#         # map1 needs to be indexed by ed_clean as well
#         map1_raw = df[df['year'] == year].drop_duplicates(subset=['ed_clean'])
#         map1 = getPct(map1_raw.set_index("ed_clean"), r1)

#         plotMap = map1.copy()
#         plotMap[f"{r1}_pct"] = 0
#         v_min, v_max, v_center = -0.1, 0.1, 0
#     else:
#         currentMap = getPct(df_temp, r1)
#         plotMap = currentMap.copy()


#         plotMap[f"{r1}_pct"] = currentMap[f"{r1}_pct"] - map1[f"{r1}_pct"]

#         actual_min = plotMap[f"{r1}_pct"].min()
#         actual_max = plotMap[f"{r1}_pct"].max()
#         v_limit = max(abs(actual_min), abs(actual_max))
#         if v_limit == 0: v_limit = 0.01
#         v_min, v_max, v_center = -v_limit, v_limit, 0


#     norm = TwoSlopeNorm(vmin=v_min, vcenter=v_center, vmax=v_max)


#     plotMap = gpd.GeoDataFrame(plotMap, geometry="geometry")


#     ax.clear()
#     cax.clear()

#     plotMap.plot(column=f"{r1}_pct", ax=ax, cax=cax, legend=True, cmap=colour, norm=norm)
#     ax.set_title(f"{r1} Change: {years[0]} to {year}")
#     ax.set_axis_off()

#     displayHandle.update(fig)
#     fig.savefig(f"{savePath}/{r1}_{year}_diverge.png", dpi=400, bbox_inches='tight')

def mapDiverge(df, year, r1, colour, isFirst, vMax, **kwargs):
    global displayHandle, map1, years

    title = f"Change in {r1} % Ireland, {2011} to {year}"
    religion_cols = ["Catholic", "No religion", "Not stated", "Other religion"]

    def getPct(data, religion):
        data = data.copy()
        total = data[religion_cols].sum(axis=1)
        data[f"{religion}_pct"] = data[religion] / total.replace(0, float("nan"))
        rawDF = data[religion].copy()
        return data, rawDF

    # Use county_key
    df_year = df[df["year"] == year].copy()
    df_year = df_year.set_index(["ed_name", "county_key"])

    if isFirst:
        map1[r1], rawDF = getPct(df_year, r1)
        plotMap = map1[r1].copy()
        plotMap[f"{r1}_pct"] = 0.0
    else:
        currentMap, rawDF = getPct(df_year, r1)
        plotMap = currentMap.copy()
        plotMap[f"{r1}_pct"] = currentMap[f"{r1}_pct"] - map1[r1][f"{r1}_pct"]

    plotMap = plotMap.reset_index()
    norm = TwoSlopeNorm(vmin=-vMax, vcenter=0, vmax=vMax)
    plotMap = gpd.GeoDataFrame(plotMap, geometry="geometry")


    n_before = len(plotMap)
    plotMap = plotMap[plotMap["geometry"].notna() & plotMap[f"{r1}_pct"].notna()]
    n_after = len(plotMap)
    if n_before != n_after:
        print(f"  [{r1} {year}] Dropped {n_before - n_after} non-renderable rows")

    # ax.clear()
    # # cax.clear()
    # cax.cla()

    # plotMap.plot(column=f"{r1}_pct", ax=ax, cax=cax, legend=False,
    #              cmap=colour, norm=norm, edgecolor='grey', linewidth=0.1)
    # sm = plt.cm.ScalarMappable(cmap=colour, norm=norm)
    # sm.set_array([])
    # # cax.cla()
    # cb = fig.colorbar(sm, cax=cax, extend='both')
    # cb.set_ticks(np.linspace(-vMax, vMax, 7))
    # cb.set_ticklabels([f'{t:.2f}%' for t in np.linspace(-vMax, vMax, 7)])
    # ax.set_title(title, fontsize=titleSize, fontweight=titleWeight)
    # ax.set_axis_off()
    #=======================================================================
    # ax.clear()
    # cax.cla() # Use cla() to keep the axis object alive

    # # Re plot map
    # plotMap.plot(column=f"{r1}_pct", ax=ax, cax=cax, legend=False,
    #              cmap=colour, norm=norm, edgecolor='grey', linewidth=0.1)

    # sm = plt.cm.ScalarMappable(cmap=colour, norm=norm)
    # sm.set_array([])


    # cb = fig.colorbar(sm, cax=cax, extend='both', use_gridspec=False, fraction=1.0)


    # cb.set_ticks(np.linspace(-vMax, vMax, 7))
    # cb.set_ticklabels([f'{t:.2f}%' for t in np.linspace(-vMax, vMax, 7)])


    # ax.set_aspect('equal')
    # ax.set_axis_off()
    #============================================================================

    ax.clear()
    cax.clear()



    plotMap.plot(column=f"{r1}_pct", ax=ax, legend=False,
                 cmap=colour, norm=norm, edgecolor='grey', linewidth=0.1)


    sm = plt.cm.ScalarMappable(cmap=colour, norm=norm)
    sm.set_array([])


    cb = fig.colorbar(sm, cax=cax, extend='both')

    cb.set_ticks(np.linspace(-vMax, vMax, 7))
    cb.set_ticklabels([f'{t:.2f}%' for t in np.linspace(-vMax, vMax, 7)])

    ax.set_title(title, fontsize=titleSize, fontweight=titleWeight)
    ax.set_axis_off()


    displayHandle.update(fig)

    # fig.savefig(f"{savePath}/{r1}_{year}_diverge2.png", dpi=900)

    # getNum(plotMap, rawDF, f"{r1}_pct", title, 'Diverged', r1, year)

    displayHandle.update(fig)
    fig.savefig(f"{savePath}/{r1}_{year}_diverge2.png", dpi=900)
    getNum(plotMap, rawDF, f"{r1}_pct", title, 'Diverged', r1, year)

# ==========================================d
# Controls
# ==========================================d

modeSelect = widgets.Dropdown(
    options=[('Standard Share', 'std'), ('Diverging Change', 'div'), ('Religious vs Secular', 'grp')],
    value='div',
    description='Mode'
)

sleepSelect = widgets.FloatSlider(
    value = 0,
    min = 0,
    max = 5,
    description = 'How long should the pause bewteen frames be?',

)
replayButton = widgets.Button(
    description='Replay',
    button_style='info',
    icon='play'
)


religionSelect = widgets.Dropdown(
    options=["Catholic", "No religion", "Not stated", "Other religion", "All"],
    value='Catholic',
    description='Religion'
)




# map(geoDF, 2011, 'Catholic')
# time.sleep(1)
# map(geoDF, 2016, 'Catholic')
# time.sleep(1)
# map(geoDF, 2022, 'Catholic')
# def mapReligion(geoDF, religion):
#   years = [2011, 2016, 2022]
#   for year in years:
#     map(geoDF, year, religion)

# ==========================================d
# Run animation
# ==========================================d
religions = ['Catholic', 'No religion', 'Other religion', 'Not stated']

def runAnimation(**kwargs):


  global religions

  mode = modeSelect.value
  sleepWoo = sleepSelect.value
  religionChoosen = religionSelect.value

  groupReligion = diverge = standard = False

  if mode == 'grp':
    groupReligion = True
  elif mode == 'div':
    diverge = True
  elif mode == 'std':
    standard = True

  # if diverge:
  #   religionColours = { # https://matplotlib.org/stable/users/explain/colors/colormaps.html
  #       'Catholic': 'RdBu',
  #       'No religion': 'PiYG',
  #       'Other religion': 'PuOr'
  #     }
  # else:
  #   religionColours = {
  #       'Catholic': 'Blues',
  #       'No religion': 'Purples',
  #       'Other religion': 'Oranges'
  #     }


  if groupReligion:
    # colour = 'plasma'
    colour = 'viridis'
    cfg = mapConfig['Grouped']
    for year in years:
      mapGrouped(geoDF, year, cfg['cmap'], cfg['std_max'])
      time.sleep(sleepWoo)

  else:
    if religionChoosen == 'All':
      for item in religions:
        # colour = religionColours[item]
        cfg = mapConfig[item]
        for year in years:
          if diverge:
            if year == years[0]:
              mapDiverge(geoDF, year, item, cfg['cmap'], True, cfg['limit'])
            else:
              mapDiverge(geoDF, year, item, cfg['cmap'], False, cfg['limit'])
          else:
            map(geoDF, year, item, cfg['std_cmap'], cfg['std_max'])
          time.sleep(sleepWoo)
    else:
      item = religionChoosen
      cfg = mapConfig[item]
      for year in years:
        if diverge:
          if year == years[0]:
            mapDiverge(geoDF, year, item, cfg['cmap'], True, cfg['limit'])
          else:
            mapDiverge(geoDF, year, item, cfg['cmap'], False, cfg['limit'])
        else:
          map(geoDF, year, item, cfg['std_cmap'], cfg['std_max'])
        time.sleep(sleepWoo)


replayButton.on_click(runAnimation)

def onChange(change):
  runAnimation()

modeSelect.observe(onChange, names='value')

religionSelect.observe(onChange, names='value')
# ==========================================d
# Display
# ==========================================d

ui = widgets.HBox([modeSelect, replayButton, sleepSelect, religionSelect])
display(ui)

# ==========================================d
# First Run
# ==========================================d

# runAnimation()
# religions = ['Catholic', 'div']
modes = ['std', 'div']
# religionsFinal = ['Catholic', 'No religion']
# for religion in religionsFinal:
  # religionSelect.value = religion
  # runAnimation()
for mode in modes:
  modeSelect.value = mode
  runAnimation()

dataframe = df[df['year'] == 2016]
print(dataframe)
noReligion2016 = dataframe[dataframe['religion'] == 'No religion'].sum()
print(f"noReligion2016 {noReligion2016}")

# =========================================================
# StatsDict
# =========================================================

statsDF = pd.DataFrame.from_dict(statsList3)
statsDF = statsDF.drop_duplicates()

print(statsDF)
save(statsDF, "statsDF2")

colsToChange = ['Avg', 'Min', 'Max', 'std']

statsRoundDF = statsDF.copy()
for col in colsToChange:
  statsRoundDF[col] = (statsRoundDF[col] * 100).round(2)
  statsRoundDF[col] = statsRoundDF[col].astype(int)
# print(statsRoundDF.describe())
# save(statsRoundDF, "statsRoundDF")

# print(statsRoundDF)

print(statsRoundDF)

# print(ageDF3.head(100))
save(statsRoundDF, "statsRoundDF_Full")

statsRoundDFcsv = statsRoundDF.copy()
statsRoundDFcsv.to_csv("statsDF.csv")

def saveCSV(savedItem, name):
  fileName = f"{name}.csv"
  fullPath = os.path.join("/content/drive/MyDrive/ESC", fileName)
  if not os.path.exists("/content/drive/MyDrive/ESC"):
    print(f"Oh.")
  with open(fullPath, 'wb') as f:
    pickle.dump(savedItem, f)
  print(f"Done.")
saveCSV(statsRoundDFcsv, "statsDF")

statsRoundDF

# lines = statsRoundDF.plot.line(x="Year", y="horse")
# def load(savedItem, name):
#   fileName = f"{name}.pkl"
#   fullPath = os.path.join("/content/drive/MyDrive/ESC", fileName)
#   if not os.path.exists("/content/drive/MyDrive/ESC"):
#     print(f"Oh.")
#   with open(fullPath, 'rb') as f:
#     savedItem = pickle.load(f)
#   print(f"Done.")
#   return savedItem
# statsRoundDF = 1
# statsRoundDF = load(statsRoundDF, "statsRoundDF_Full")
# statsRoundDF = load(statsRoundDF_Full)

prePivotSTD = statsRoundDF[(statsRoundDF['Mode'] == 'Standard') & (statsRoundDF['Religion'].isin(['Catholic', 'No religion']))]
# prePivotSTD = prePivotSTD.drop(columns=['Max Loc', 'Total', 'Min Loc', 'Min', 'Max', 'Avg', 'Mode'])
prePivotSTD = prePivotSTD[['Religion', 'Year', 'std']]
print(prePivotSTD)
pivotSTD = prePivotSTD.pivot(index='Year', columns='Religion', values='std')
print("pivotSTD", pivotSTD)

lines = pivotSTD.plot.line()
# ==========================================
# CELL 5 — DIVERGENCE ANALYSIS
# ==========================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.patches import Patch
import matplotlib.gridspec as gridspec


for year in [2011, 2016, 2022]:
    mask = geoDF["year"] == year
    total = geoDF.loc[mask, ["Catholic", "No religion", "Not stated", "Other religion"]].sum(axis=1)
    geoDF.loc[mask, "Catholic_pct"]    = (geoDF.loc[mask, "Catholic"]    / total) * 100
    geoDF.loc[mask, "NoRelig_pct"]     = (geoDF.loc[mask, "No religion"] / total) * 100

# sane check
print("Catholic_pct sample:", geoDF["Catholic_pct"].describe().round(1))


religions_band = {
    "Catholic":    ("Catholic_pct",  cm.get_cmap("Blues")),
    "No religion": ("NoRelig_pct",   cm.get_cmap("Purples")),
}

percentiles = {col: {} for col in ["Catholic_pct", "NoRelig_pct"]}
for year in [2011, 2016, 2022]:
    for col in percentiles:
        vals = geoDF[geoDF["year"] == year][col].dropna()
        percentiles[col][year] = {
            "p10": vals.quantile(0.10),
            "p25": vals.quantile(0.25),
            "p50": vals.quantile(0.50),
            "p75": vals.quantile(0.75),
            "p90": vals.quantile(0.90),
            "std": vals.std(),
        }


def make_pctDF(col):
    rows = []
    for year in [2011, 2016, 2022]:
        row = {"Year": year}
        row.update(percentiles[col][year])
        rows.append(row)
    return pd.DataFrame(rows)

cathDF = make_pctDF("Catholic_pct")
atheDF = make_pctDF("NoRelig_pct")

print("\nCatholic percentiles:\n", cathDF.round(1))
print("\nNo religion percentiles:\n", atheDF.round(1))


fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=False)
fig.suptitle("Geographic Variation in % Catholicism vs Non Religion Ireland, 2011–2022",
             fontsize=14, fontweight="bold", y=1.02)

plot_specs = [
    (axes[0], cathDF,  "Greens",   "forestgreen",  "% Catholic",    "Catholic"),
    (axes[1], atheDF,  "Blues", "steelblue","% No Religion", "No Religion"),
]


for ax, df, cmap_name, colour, ylabel, title in plot_specs:
    cmap = cm.get_cmap(cmap_name)

    ax.fill_between(df["Year"], df["p10"], df["p90"],
                    alpha=0.15, color=colour, label="10th–90th percentile")
    ax.fill_between(df["Year"], df["p25"], df["p75"],
                    alpha=0.35, color=colour, label="25th–75th percentile")
    ax.plot(df["Year"], df["p50"],
            color=colour, linewidth=2.5, marker="o", markersize=7, label="Median ED")


    spread_2011 = df.loc[df["Year"]==2011, "p90"].values[0] - df.loc[df["Year"]==2011, "p10"].values[0]
    spread_2022 = df.loc[df["Year"]==2022, "p90"].values[0] - df.loc[df["Year"]==2022, "p10"].values[0]
    ax.text(0.97, 0.05,
            f"Spread: {spread_2011:.0f}pp → {spread_2022:.0f}pp",
            transform=ax.transAxes, ha="right", fontsize=9,
            color="dimgrey", style="italic")

    ax.set_xticks([2011, 2016, 2022])
    ax.set_xlabel("Census Year", fontsize=10)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.set_title(title, fontsize=titleSize, fontweight=titleWeight)
    ax.legend(fontsize=8, loc="upper right" if title == "Catholic" else "upper left")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

plt.tight_layout()
plt.savefig(f"{savePath}/divergence_bands.png", dpi=400, bbox_inches="tight")
plt.show()


prePivotSTD = statsRoundDF[
    (statsRoundDF["Mode"] == "Standard") &
    (statsRoundDF["Religion"].isin(["Catholic", "No religion", "Other religion"]))
][["Religion", "Year", "std"]]

pivotSTD = prePivotSTD.pivot(index="Year", columns="Religion", values="std")
print("\nStd dev table:\n", pivotSTD)

std_colours = {
    "Catholic":       "steelblue",
    "No religion":    "mediumpurple",
    "Other religion": "darkorange",
}

fig, ax = plt.subplots(figsize=(10, 5))
for col in pivotSTD.columns:
    ax.plot(pivotSTD.index, pivotSTD[col],
            color=std_colours.get(col, "grey"),
            marker="o", linewidth=2.5, markersize=7, label=col)

ax.set_xticks([2011, 2016, 2022])
ax.set_xlabel("Census Year", fontsize=10)
ax.set_ylabel("Standard Deviation of ED-level %", fontsize=10)
ax.set_title("Increasing Spread: Standard Deviation Across Electoral Divisions",
             fontsize=12, fontweight="bold")
ax.legend(fontsize=9)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
plt.tight_layout()
plt.savefig(f"{savePath}/std_divergence.png", dpi=400, bbox_inches="tight")
plt.show()


print("\n=== KEY STATS FOR SLIDE 4 ===")
for col, label in [("Catholic_pct", "Catholic"), ("NoRelig_pct", "No religion")]:
    print(f"\n{label}:")
    for year in [2011, 2016, 2022]:
        p = percentiles[col][year]
        print(f"  {year}: median={p['p50']:.1f}%, "
              f"spread (10-90)={p['p10']:.1f}%–{p['p90']:.1f}%, "
              f"std={p['std']:.1f}pp")

# def load(savedItem, name):
#   fileName = f"{name}.pkl"
#   fullPath = os.path.join("/content/drive/MyDrive/ESC", fileName)
#   if not os.path.exists("/content/drive/MyDrive/ESC"):
#     print(f"Oh.")
#   with open(fullPath, 'rb') as f:
#     savedItem = pickle.load(f)
#   print(f"Done.")
#   return savedItem
# statsRoundDF = 1
# statsRoundDF = load(statsRoundDF, "statsRoundDF")
statsRoundDF = statsRoundDF.copy()

# colsToChange = ['Avg', 'Min', 'Max', 'std']
# for col in colsToChange:
#   statsRoundDF[col] = (statsRoundDF[col] * 100).round(0)
#   statsRoundDF[col] = statsRoundDF[col].astype(int)

print(statsRoundDF)
# ===========================================
# Key Stats
# ===========================================

# maxDeclineDiv = statsRoundDF['Min'].min()
# mDD = df.loc[df[col] == maxDeclineDiv, 'Min Loc'].iloc[0]

def find(df, Religion, mode, col, fMode):
  if fMode == 'Min':
    if mode == 'Div':
      value = df['col'].min()
      word = 'declined'
    elif mode == 'Std':
      value = df['col'].min()
      word = 'declined'
  if fMode == 'Max':
    value = df[col].max()
    word = 'risen'


  location = df.loc[df[col] == value, 'ED_ENGLISH'].iloc[0]
  print(f"{Religion} has {word} by {value}% in {location}")
  print(f"{Religion} has {word} by {value}% in {location}")

#=============================================================================
# Religion over time
#=============================================================================

debugLong = True
debugGraph = True
debugGraph2 = True
debugLight = True
from google.colab import drive
drive.mount("/content/drive", force_remount=True)
religionExcl = pd.ExcelFile(file_path)

print(religionExcl.sheet_names)


#===================================================
# getting data
#===================================================

# longTimeDF = pd.read_excel(file_path, sheet_name="Religion1861_2016")
longTimeDF = pd.read_excel(file_path, sheet_name="E8085")
longTimeDF2 = longTimeDF.copy()
columnListLong = longTimeDF.columns.tolist()
if debugGraph:
  print(f"columnListLong,  {columnListLong}")
longTimeDF2 = longTimeDF2.drop(columns='Statistic Label')
longTimeDF2 = longTimeDF2.drop(columns='UNIT')

yearStart = 1960
religionCol = 'Religion'
yearCol = 'CensusYear'
if debugGraph:
  print(longTimeDF2[religionCol].head(80))
longRunState = longTimeDF2 #longTimeDF2[longTimeDF2['County'] == 'State']
longRunState = longRunState[longRunState[yearCol] >= yearStart]

catholicOverTimeRaw = longRunState[longRunState[religionCol] == 'Roman Catholic']
if debugLong:
  print(f"catholicOverTimeRaw {catholicOverTimeRaw}")
atheistOverTimeRaw = longRunState[longRunState[religionCol] == 'No religion']

toRemove = ['Roman Catholic', 'No religion', 'All religious denominations', 'Other', 'All religions', 'Not stated']
otherOverTimeRaw = longRunState[~longRunState[religionCol].isin(toRemove)].dropna()

if debugGraph2:
  colList = otherOverTimeRaw.columns.tolist()
  print(f"WOOOOO other raw cols: \n {colList} \n----")
otherOverTimeSummed = otherOverTimeRaw.groupby('CensusYear')['VALUE'].sum().reset_index()
if debugLight:
  print(f"Other over summed: WOOOOOOO {otherOverTimeSummed} \n ~~~~~~~~ ")
#===================================================
# Analysis
#===================================================

def getPct(religionRaw):
  totalStatePop = longRunState[longRunState[religionCol] == 'All religions']
  if debugDeep:
    print(f"-----")
    print(f"totalStatePop {totalStatePop['VALUE']}")
    print(f"-----")
  pctDecimal = religionRaw['VALUE'].reset_index(drop=True) / totalStatePop['VALUE'].reset_index(drop=True)
  pct = pctDecimal * 100
  return pct
def getPctSeries(values_series, years_series):
  totalStatePop = longRunState[longRunState[religionCol] == 'All religions']
  total_vals = totalStatePop.set_index(yearCol)['VALUE']
  return (values_series.values / total_vals.loc[years_series.values].values) * 100

otherOverTimePct = getPctSeries(
    otherOverTimeSummed['VALUE'],
    otherOverTimeSummed['CensusYear']
)
atheistOverTimePct = getPct(atheistOverTimeRaw)
# atheism2016 = atheistOverTimePct[atheistOverTimePct['Year'] == 2016]
atheism2016 = atheistOverTimePct.tolist()
if debugGraph:
  print(f"\n WOOOOOO atheistOverTimePct {atheistOverTimePct}\n atheistOverTimeRaw {atheistOverTimeRaw} =-----\n")
atheism2016 = atheism2016[-1]
# otherOverTimePct = getPct(otherOverTimeSummed)

catholicOverTimePct = getPct(catholicOverTimeRaw)

if debugLong == True:
  print(f"atheism2016 {atheism2016}")
  print(f"catholicOverTimePct {catholicOverTimePct}")
yearsLong = catholicOverTimeRaw[yearCol]
if debugGraph:
  print(f"yearsLong {yearsLong}, type {type(yearsLong)}")
# yearsLong = yearsLong[yearsLong['Year'] >= yearStart]

#===================================================
# Adding 2022
#===================================================

# popByYear = statsRoundDF.groupby("Year")[["Catholic", "No religion", "Not stated", "Other religion"]].sum()
# popByYear["totalPop"] = popByYear.sum(axis=1)

# #getting pct per religion

# standardDF = statsRoundDF[statsRoundDF["Mode"] == "Standard"].copy()
# standardDF["nationalPCT"] = standardDF.apply(
#     lambda row: (row["Total"] / popByYear.loc(row["Year"], "totalPop")) * 100,
#     axis=1
# )
# if debugGraph:
#   print("standardDF", standardDF[["Religion", "Year", "nationalPCT"]])
# ===================================================================================================
# standard2022 = statsRoundDF[
#     (statsRoundDF["Mode"] == "Standard") &
#      (statsRoundDF["Year"] == 2022)][["Religion", "Total"]]
# total2022 = standard2022["Total"].sum()

# if debugGraph:
#   print("standard2022 is ==== \n", standard2022)
# catholic2022_pct  = (standard2022.loc[standard2022["Religion"] == "Catholic",    "Total"].values[0] / total2022) * 100
# atheist2022_pct   = (standard2022.loc[standard2022["Religion"] == "No religion", "Total"].values[0] / total2022) * 100


# ===================================================================================================
totals2022 = wideDF[wideDF["year"] == 2022][["Catholic", "No religion", "Not stated", "Other religion"]].sum()
total2022 = totals2022.sum()

catholic2022_pct = (totals2022["Catholic"]    / total2022) * 100
atheist2022_pct  = (totals2022["No religion"] / total2022) * 100
other2022_pct = (totals2022["Other religion"] / total2022) * 100

if debugLight:
  print(f"Catholic 2022: {catholic2022_pct:.1f}%")
  print(f"No religion 2022: {atheist2022_pct:.1f}%")
  print(f"Other religion 2022: {other2022_pct:.1f}%")
# Extend the existing series
yearsExtended    = list(yearsLong) + [2022]
catholicExtended = list(catholicOverTimePct) + [catholic2022_pct]
atheistExtended  = list(atheistOverTimePct)  + [atheist2022_pct]
otherExtended = list(otherOverTimePct) + [other2022_pct]
# otherExtended = otherExtended.dropna()
if debugGraph2:
  print(f"catholicExtended {catholicExtended}")
  print(f"atheistExtended {atheistExtended}")
  print(f"otherExtended {otherExtended}")

print(f"Catholic 2022: {catholic2022_pct:.1f}%")
print(f"No religion 2022: {atheist2022_pct:.1f}%")

print(f"longTimeDF 2016 Catholic: {catholicOverTimePct.tolist()[-1]:.1f}%")
print(f"statsDF 2016 Catholic: {(statsRoundDF[(statsRoundDF['Mode']=='Standard') & (statsRoundDF['Year']==2016) & (statsRoundDF['Religion']=='Catholic')]['Total'].values[0] / statsRoundDF[(statsRoundDF['Mode']=='Standard') & (statsRoundDF['Year']==2016)]['Total'].sum() * 100):.1f}%")


#===========================================================================================
#                            max min and graphs
#===========================================================================================
# title =
#=----------------------
# Bar Chart
#=----------------------
religionsForBar = ["Catholic", "No religion", "Other religion"]
colours = {
    "Catholic": 'forestgreen',
    "No religion": 'steelblue',
    "Other religion": 'orange'
}

barColours = [colours[religion] for religion in religionsForBar]
religionFirstYear = [catholicExtended[0], atheistExtended[0], otherExtended[0]]
plt.figure(figsize=(10,4))
fig, ax = plt.subplots()
religionBars = ax.bar(religionsForBar, religionFirstYear, color=barColours)
ax.set_ylabel("% Religion")
ax.set_ylim(0, 100)
ax.set_title(f"% Ireland of Identfying as Religions, Census {yearStart}", fontsize=titleSize, fontweight=titleWeight)
ax.bar_label(religionBars, fmt='{:,.2f}%')
# ax.set_xticks(religionFirstYear, labels=religionsForBar)
plt.savefig(f"{savePath}/1960_bar_chart.png", dpi=900, bbox_inches="tight")
plt.show()
#=----------------------
# Plot line
#=----------------------
import numpy as np

maxCatholic = np.max(catholicExtended)
mincatholic = np.min(catholicExtended)
differenceAbs = maxCatholic - mincatholic
differencePct = 1 - (mincatholic / maxCatholic)
print(f"maxCatholic: {maxCatholic}, mincatholic {mincatholic}, difference (absolute terms):, {differenceAbs}, difference (pct decrease) {differencePct}")
plt.plot(yearsExtended, catholicExtended, color='limegreen')
plt.plot(yearsExtended, atheistExtended, color='white')
# plt.plot(yearsExtended, otherExtended, color='orange')
plt.title(f"% Ireland of Identfying as Religions, Census {yearStart} - 2022")
plt.ylabel("% Catholic")
plt.xlabel("Year")
plt.legend()
plt.ylim(0, 100)
plt.show()

# print(catholicOverTimeRaw)
print(f"catholicOverTimePct {catholicExtended}")

# from matplotlib.animation import FuncAnimation
# from scipy.interpolate import CubicSpline
# from IPython.display import HTML
# import numpy as np
from matplotlib.animation import FFMpegWriter

plt.close('all')

x = np.array(yearsExtended)
x_smooth = np.linspace(x.min(), x.max(), 300)

y_catholic = np.clip(CubicSpline(x, catholicExtended)(x_smooth), 0, 100)
y_atheist  = np.clip(CubicSpline(x, atheistExtended)(x_smooth),  0, 100)
y_other    = np.clip(CubicSpline(x, otherExtended)(x_smooth),    0, 100)

fig, ax = plt.subplots(figsize=(10, 6))
line_c, = ax.plot([], [], color=colours['Catholic'], label='Catholic')
line_a, = ax.plot([], [], color=colours['No religion'], label='No religion')
line_o, = ax.plot([], [], color=colours['Other religion'],    label='Other religion')


txt_c = ax.text(0, 0, '', color=colours['Catholic'], fontsize=11, fontweight='bold')
txt_a = ax.text(0, 0, '', color=colours['No religion'], fontsize=11, fontweight='bold')
txt_o = ax.text(0, 0, '', color=colours['Other religion'], fontsize=11, fontweight='bold')

ax.set_xlim(x_smooth[0], x_smooth[-1] + 2)   # little extra room for labels

# ax.set_xlim(x_smooth[0], x_smooth[-1])
ax.set_ylim(0, 100)
ax.set_title("% Ireland Identifying as Religion, 1960–2022", fontsize=titleSize, fontweight=titleWeight)
ax.set_xlabel("Year")
ax.set_ylabel("%")

# ax.legend(loc='upper left', bbox_to_anchor=(0.5, -0.15), ncol=3)  # below plot

# ax.legend(loc='center right')
ax.legend(
    loc='upper center',
    fontsize='large',
    bbox_to_anchor=(0.5, -0.18),
    ncol=3,
    columnspacing=5.0,
    # mode="expand",
    borderaxespad=0.
)

def update(frame):
    xs = x_smooth[:frame]

    line_c.set_data(xs, y_catholic[:frame])
    line_a.set_data(xs, y_atheist[:frame])
    line_o.set_data(xs, y_other[:frame])

    if frame > 0:
        x_now = x_smooth[frame - 1]

        # Catholic label
        yc = y_catholic[frame - 1]
        txt_c.set_position((x_now + 0.5, yc))
        txt_c.set_text(f"{yc:.1f}%")

        # Atheist label
        ya = y_atheist[frame - 1]
        txt_a.set_position((x_now + 0.5, ya))
        txt_a.set_text(f"{ya:.1f}%")

        # Other label
        yo = y_other[frame - 1]
        txt_o.set_position((x_now + 0.5, yo))
        txt_o.set_text(f"{yo:.1f}%")

    return line_c, line_a, line_o, txt_c, txt_a, txt_o

ani = FuncAnimation(fig, update, frames=len(x_smooth), interval=20, blit=False)
# ax.legend(loc='upper left', bbox_to_anchor=(1, 1.4))  # right of plot
writer = FFMpegWriter(fps=60, metadata=dict(artist='Me'), bitrate=3000)
plt.tight_layout()
ani.save(f"{savePath}/religion_over_time2.mp4", writer=writer)
HTML(ani.to_jshtml())